volumes:
  postgres_data:

services:

  postgres:
    image: postgres:18
    container_name: velo-postgres
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: velo-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: velo-app
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/ecommerce_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
